bin/coverage_report_single.py
bin/coverage_stats_single.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/4)
Fixes #3

Added option to pass threshold values

---

bin/coverage_run_stats.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/5)
Changes to fix run stats script for using variable thresholds

Variable thresholds for run stats

---

.gitattributes
README.md
bin/coverage_report_single.py
data/templates/single_template.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/8)

v1.0.1 bug fixes

---

data/templates/single_template.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/9)

annoying typo

---

README.md
bin/coverage_report_single.py
data/templates/single_template.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/10)

Add clinical summary text to reports, handle single exon gene plotting

---

bin/coverage_report_single.py
data/templates/single_template.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/11)

unbin data for more accurate plotting, improve report wording

---

README.md
bin/coverage_report_single.py
bin/coverage_stats_single.py

- Adds parallelisation to both generating single sample stats and full gene plots for super speedy running
- Fixes #15 - typo in readme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/16)

Add parallelisation

---

bin/coverage_report_single.py

Refactor load_files() function to split into multiple individual functions
New class getData() with the functions:
- read_exon_stats -> read in single sample exon stats
- read_gene_stats -> read in single sample gene stats
- read_raw_coverage -> read in full annotated bed file
- read_bootstrap -> read in bootstrap to for HTML styling
- read_template -> read in HTML report template
- get_build_and_stats -> parse flagstats and ref. build from gene stats header
- get_panel_name -> get panel name from bed file
- get_snp_vcfs -> get str of vcf names
- get_athena_ver -> get verison of Athena used
- check_threshold -> checks threshold value given is valid against exon/gene stats
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Refactor importing data to separate class of functions

---

bin/coverage_report_single.py

- Adds gene coverage % to clinical summary text
- Fixes #28
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/31)

1.2 add gene % to summary text

---

data/templates/single_template.html

- change random colour of low exon plot lines to not be pale => more visible
- manually generate y-axis tick values to ensure they are appropriate, cases where coverage much lower than threshold line and axis values were limited by coverage value and not threshold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/37)

1.2 - Tweak low exon plots

---

bin/coverage_report_single.py

- removes call to generate sub threshold plots, missed from previous PR when added multi-processing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/39)

remove call to generate sub threshold plots

---

README.md

- Improve documentation of required input file structure
- Add link to page to create exons nirvana equivalent file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/50)

1.2 - Update readme

---

data/templates/single_template.html

- fixes UTF8 issue #30 that was previously fixed in PR #32 and subsequently overwritten in a merge conflict
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/52)

1.2.1 - fix UTF8

---

README.md
bin/coverage_report_single.py
bin/load_data.py
bin/version.py
data/templates/single_template.html

- Optional per-chromosome coverage plotting added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/59)

Implemented per-chromosome coverage plotting

---

data/templates/single_template.html

Closes #62 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/64)

Add copy to clipboard button to tables

---

bin/annotate_bed.py
bin/coverage_report_single.py
bin/coverage_stats_single.py
bin/load_data.py
bin/version.py
data/templates/single_template.html
requirements.txt

- switch from using gene & exon to transcript & exon for calculating coverage, allows for adding multiple transcripts to a report for a single gene
- handle non-integer exons (i.e. adding introns and having no exon number)
- handle no underscore in name causing index error - fixes #54 
- fixes #53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/65)

Handle multiple transcripts

---

bin/coverage_report_single.py
bin/coverage_stats_single.py

- fix to use natural sorting of dataframes before generating full gene plots to preserve correct ordering of exons
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/66)

1.4.1 - fix sorting

---

bin/version.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/67)

bump version to 1.4.1

---

bin/coverage_report_single.py

- Fixes #68 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/78)

Fix summary plot label overlap

---

bin/coverage_report_single.py
data/templates/single_template.html

- adds export to csv buttons to all tables
- adds optional drop down list filter to all gene plots to show filtered list of gene panels
- adds regex searching for dataTables - fixes #74 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/77)

gene plots panel filter

---

.gitignore
bin/coverage_report_single.py
bin/load_data.py
data/templates/single_template.html

##Summary
PR of everything for v1.5.0 release
##Changes
- Fixes #68
- Fixes #71 
- Adds optional panel filter to all genes plots - closes #74
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/athena/79)

v1.5.0 release
